spring:
  application:
    name: timedeal-service
  profiles:
    default: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
