server:
  port: 8011
spring:
  application:
    name: timedeal-service
  profiles:
    default: prod
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: update
